spring:
  application:
    name: security-security
  datasource:
    #url: jdbc:mysql://localhost:3306/security-jwt-auth?useUnicode=true&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #url: jdbc:h2:mem:security-security
    url: jdbc:h2:file:./data/security-security
    driverClassName: org.h2.Driver
    username: root
    password: 25810*
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
